version: "3.7"
services:
  release:
    build: 
      context: .
      dockerfile: ./release.Dockerfile
    image: frenetiq/caolo-release:bleeding
    env_file: docker.env
    depends_on:
      - db
  api:
    build: 
      context: .
      dockerfile: ./api.Dockerfile
    image: frenetiq/caolo-api:bleeding
    env_file: docker.env
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      CAO_SIM_URL: sim:50051
    ports:
      - "8000:8000"
    depends_on:
      - cache
      - db

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      timeout: 1s
      retries: 3
      start_period: 5s

  sim:
    build: 
      context: .
      dockerfile: ./sim.Dockerfile
    image: frenetiq/caolo-sim:bleeding
    env_file: docker.env
    depends_on:
      - cache
      - db
    ports:
      - "50051:50051"

  cache:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  db-data:
    driver: local
