FROM python:3.9-alpine AS build

RUN apk add curl gcc libpq protobuf build-base libffi-dev
RUN protoc --version

RUN pip install -U setuptools pip virtualenv

WORKDIR /caolo
# install Rust compiler
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup update
RUN rustc --version
RUN cargo --version

COPY ./protos/ ./protos/
COPY ./web/ ./web/

ENV CAO_PROTOS_PATH=/caolo/protos
WORKDIR /caolo/web

RUN python -m venv .env
RUN .env/bin/pip install . --no-cache-dir

FROM python:3.9-alpine

WORKDIR /caolo/web

RUN apk add gcc libpq

COPY --from=build /caolo/web/start.sh ./
COPY --from=build /caolo/web/ ./

ENV PATH="/caolo/web/.env/bin:$PATH"

RUN pip install gunicorn
RUN chmod +x start.sh

ENTRYPOINT [ "sh", "./start.sh"]
