FROM python:3.9-slim

RUN apt-get update
RUN apt-get install curl gcc libpq-dev protobuf-compiler -y --fix-missing
RUN protoc --version

RUN pip install gunicorn

WORKDIR /caolo
# install Rust compiler
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup update
RUN rustc --version
RUN cargo --version

COPY ./protos/ ./protos/
COPY ./web/ ./web/

ENV CAO_PROTOS_PATH=/caolo/protos
WORKDIR /caolo/web

RUN pip install .
RUN chmod +x start.sh

ENTRYPOINT [ "sh", "./start.sh"]
