FROM rust:latest

EXPOSE 8000

RUN USER=root cargo new --bin worker

WORKDIR /worker

COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./rust-toolchain ./rust-toolchain

COPY ./simulation/ ./simulation/
COPY ./worker/ ./worker/
COPY ./api/ ./api/
COPY ./cao-lang/ ./cao-lang/
COPY ./webservice/ ./webservice/

RUN cargo build --release

ENTRYPOINT ["./target/release/caolo-worker"]
