"""empty message

Revision ID: 094338a06c4d
Revises: 7699d992b4d8
Create Date: 2020-01-20 19:53:49.393839

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '094338a06c4d'
down_revision = '7699d992b4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'program', "ast", nullable=False, new_column_name="program")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'program', "program", nullable=False, new_column_name="ast")
    # ### end Alembic commands ###
