"""empty message

Revision ID: 2147ce1fa522
Revises: fc6358c6a954
Create Date: 2020-01-11 12:11:47.531673

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2147ce1fa522'
down_revision = 'fc6358c6a954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('compiled', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'compiled')
    # ### end Alembic commands ###
