"""empty message

Revision ID: 7699d992b4d8
Revises: 2147ce1fa522
Create Date: 2020-01-11 20:10:49.673332

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7699d992b4d8'
down_revision = '2147ce1fa522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'name')
    # ### end Alembic commands ###
