FROM rust:latest AS build

RUN apt-get update
RUN apt-get install sudo postgresql postgresql-contrib -y
RUN service postgresql start

WORKDIR /caolo

COPY ./rust-toolchain ./rust-toolchain
# cache the toolchain
RUN cargo --version

WORKDIR /caolo/web
RUN cargo install diesel_cli --root . --no-default-features --features="postgres"

ENV DATABASE_URL=postgres://postgres:postgres@localhost:5432/caolo

WORKDIR /caolo
COPY ./web/build.sh ./
COPY ./migrations/ ./migrations/
COPY ./messages/ ./messages/
COPY ./web/ ./web/

WORKDIR /caolo/web
RUN bash ./build.sh

# ---------- Copy the built binary to a scratch container, to minimize the image size ----------

FROM ubuntu:20.04
WORKDIR /caolo
RUN apt-get update
RUN apt-get install curl libpq-dev -y

COPY ./migrations/ ./migrations/
COPY ./web/release.sh ./
COPY --from=build /caolo/web/bin/ ./

ENTRYPOINT ["./caolo-web"]
