FROM rust:latest AS build

# install protoc
WORKDIR /usr/protocinstall
ENV PROTOC_ZIP=protoc-3.11.3-linux-x86_64.zip
RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/$PROTOC_ZIP
RUN unzip -o $PROTOC_ZIP -d /usr/local bin/protoc

WORKDIR /caolo

COPY ./rust-toolchain ./rust-toolchain
# cache the toolchain
RUN cargo --version

WORKDIR /caolo/web
RUN cargo install diesel_cli --root . --no-default-features --features="postgres"

WORKDIR /caolo
COPY ./protos/ ./protos/
COPY ./web/ ./web

WORKDIR /caolo/web
RUN cargo check
RUN cargo install --path . --root . --no-default-features --features="with-serde"

# ---------- Copy the built binary to a scratch container, to minimize the image size ----------

FROM ubuntu:20.04
WORKDIR /caolo
COPY ./migrations/ ./migrations/
COPY ./web/release.sh ./
COPY --from=build /caolo/web/bin/ ./
